name: Update Store JSON

on:
  repository_dispatch:
    types: [update-store]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # إعطاء البوت صلاحية حفظ الملفات في المستودع

    steps:
      - name: تحميل ملفات المستودع
        uses: actions/checkout@v4

      - name: سحب بيانات المتجر من Firebase
        run: |
          USERNAME="${{ github.event.client_payload.username }}"
          echo "جاري سحب بيانات المتجر: $USERNAME"

          # إنشاء مجلد stores إذا لم يكن موجوداً
          mkdir -p stores
          
          # رابط قاعدة بياناتك مع المفتاح السري لضمان نجاح السحب
          FIREBASE_URL="https://nalsh-store-default-rtdb.europe-west1.firebasedatabase.app/stores/${USERNAME}.json?auth=abWaY3WlYFKCeC72RKg8w8pU67IEGKvnrPGUyY0N"
          
          # سحب البيانات وحفظها في ملف JSON
          curl -s "$FIREBASE_URL" -o "stores/${USERNAME}.json"

      - name: حفظ التعديلات ورفعها للمستودع
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Nalsh Bot"
          
          git add stores/${{ github.event.client_payload.username }}.json
          
          git diff --quiet && git diff --staged --quiet || git commit -m "🚀 تحديث آلي لمنتجات المتجر: ${{ github.event.client_payload.username }}"
          
          git push
